name: Build and run tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        include:
          - runtime: arm64
            os: macos-12
            go-version: 1.17.6
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build
      run: |
          make build
    - name: Test
      run: |
          lscpu
          install_name_tool -id $(pwd)/wasmer/libwasmer_darwin_amd64.dylib wasmer/libwasmer_darwin_amd64.dylib
          install_name_tool -id $(pwd)/wasmer/libwasmer_darwin_arm64.dylib wasmer/libwasmer_darwin_arm64.dylib
          make test
