name: Build and run tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-18.04
            go-version: 1.15.x
          - runtime: osx-arm64
            os: macos-11
            go-version: 1.15.x
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: |
          make test-short
