name: Build and run tests (MacOS ARM64)

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.20.7]
    runs-on: macos-13-xlarge
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Test
        run: |
          VMEXECUTOR="wasmer2" go test ./... -failfast -p 1
